entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

tls:
  certificates:
    - certFile: "/certs/fullchain.pem"
      keyFile: "/certs/privkey.pem"
